
version: '3.7'
services:

  # Unfortunately docker-compose v3 dropped extends
  # See: https://github.com/moby/moby/issues/31101
  food_client:
    build:
      context: .
      dockerfile: Dockerfile
    image: oarthurnardi/app
    container_name: client
    command: "npm run serve"
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"