
version: '3.7'
services:

  # Unfortunately docker-compose v3 dropped extends
  # See: https://github.com/moby/moby/issues/31101
  food_client:
    build:
      context: .
      dockerfile: Dockerfile
    image: oarthurnardi/app
    container_name: client
    command: "npm run serve"
    environment:
      NODE_ENV: "development"
      CLIENT_ID: "CXPHCCC2AKJ2LWBEMXEOZVS1FJDYDI5A5QUI2QFGNVJ1EKAI"
      CLIENT_SECRET: "1WHPUJ2CKQCI3OEZGMOK3TIWHJZAASO2EXVVSNBX4JNBYLLE"
      VERSION_DATE: 20181110
    ports:
      - "8080:8080"
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"